### PR TITLE
fix calculation of getPathSet

### LINKED ISSUE #28: Incorrect calculation of getPathSet
https://github.com/nevadskiy/laravel-tree/blob/626d9c5a5b711651c807e28002904a63d6615ee6/src/ValueObjects/Path.php#L93

The index of array_slice should start from 1 in order to obtain the correct result.

### PR DESCRIPTION
**Pull request by illambo**
resolve #28

### CODE REVIEW

**Comment by nevadskiy** [comment]
@illambo your test passes successfully even on the old code. I don't see what exactly is broken.

**Comment by illambo** [comment]
In my local project with mysql connection return first slice an empty string. When I can I give you more info. Thanks

**Comment by nevadskiy** [comment]
Could you write a phpunit test describing your specific case?

**Comment by illambo** [comment]
Hi, for me the test fails if i revert the fix.
Doesn't it fail you?

Screenshot 2023-12-19 alle 19 05 11

**Comment by nevadskiy** [comment]
@illambo you are absolutely right. my bad.

**Comment by illambo** [comment]
No problem, thanks for the package!

**Pull request merged**
